### ISSUE TITLE
Support for iot-gate-imx8plus

### ISSUE THREAD

**Issue by phishstang65** [compulab-yokneam/meta-compulab-hab#2]
Hi - I see that the compatible machines in these HAB support recipes do not include the iot-gate-imx8plus.

Will this layer work for secure boot with your iot-gate-imx8plus product? Thank you.

`MACHINE=iot-gate-imx8plus`

**Comment by vraevsky** [comment]
Added imx8mp support:
https://github.com/compulab-yokneam/meta-compulab-hab

**Comment by phishstang65** [comment]
Thanks for the update. I did just now successfully pull and build. One thing that I hit was that U-Boot was bumped from 2021.04 to 2022.04 and my Yocto build machine needed to have the gnutls dev package installed. Just wanted to make a note of it here in case others have the same issue.

`sudo apt install libgnutls28-dev -y`

```
| /home/developer/compulab-nxp-bsp/build-iot-gate-imx8plus/tmp/work/iot_gate_imx8plus-poky-linux/u-boot-compulab/2022.04-r0/git/tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
|  #include <gnutls/gnutls.h>
|           ^~~~~~~~~~~~~~~~~
| compilation terminated.
```
